# Solomon X Bootstrap Token Generator
# Generates TPM-sealed boot token and Ed25519 identity keypair
# Run this script in PowerShell as Administrator

Write-Host "=== Solomon X Bootstrap Token Generator ===" -ForegroundColor Cyan
Write-Host "This script generates the boot token and identity key for Solomon X." -ForegroundColor Yellow
Write-Host "NOTE: For production, this should be run as Administrator to use TPM 2.0." -ForegroundColor Yellow
Write-Host ""

# Check if running as Administrator
$isAdmin = ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
if (-not $isAdmin) {
    Write-Warning "This script is not running as Administrator. TPM operations may fail."
    Write-Warning "Please restart PowerShell as Administrator and try again."
    # Continue anyway for MVP simulation
}

# Define paths
$tokenDir = Join-Path $env:ProgramData "solomon"
$tokenPath = Join-Path $tokenDir "boot_token"
$keyPath = Join-Path $tokenDir "identity_keypair"

# Create directory if it doesn't exist
if (-not (Test-Path $tokenDir)) {
    New-Item -ItemType Directory -Path $tokenDir -Force | Out-Null
    Write-Host "Created directory: $tokenDir" -ForegroundColor Green
}

# Step 1: Generate random token seed (32 bytes)
Write-Host "Generating random token seed..." -ForegroundColor Cyan
$tokenSeed = New-Object byte[] 32
[System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($tokenSeed)
$tokenSeedHex = [BitConverter]::ToString($tokenSeed).Replace('-', '').ToLower()

# Save token seed to file (in production, this would be sealed to TPM)
[IO.File]::WriteAllBytes($tokenPath, $tokenSeed)
Write-Host "Token seed saved to: $tokenPath" -ForegroundColor Green
Write-Host "Token seed (hex): $tokenSeedHex" -ForegroundColor DarkCyan

# Step 2: Derive Ed25519 keypair from token seed (using HKDF-SHA256)
Write-Host "`nDeriving Ed25519 identity keypair..." -ForegroundColor Cyan

# In production: would use libsodium or similar to derive key
# For MVP: we'll use a simple hash for demonstration (NOT SECURE - for demo only)
# WARNING: This is NOT cryptographically secure! Use proper key derivation in production.
$hashAlgorithm = [System.Security.Cryptography.SHA256]::Create()
$hashInput = $tokenSeed + [Text.Encoding]::UTF8.GetBytes("solomon-identity-v1")
$hashBytes = $hashAlgorithm.ComputeHash($hashInput)
$privateKeyBytes = $hashBytes[0..31] # Take first 32 bytes

# Generate a mock public key (in production: would derive from private key)
# For Ed25519, public key is derived from private key via curve25519
# For MVP: we'll just duplicate the private key as a placeholder
$publicKeyBytes = $privateKeyBytes.Clone() # Placeholder - NOT REAL

# Save keypair (in production: would save private key securely, public key can be shared)
$keypairBytes = $privateKeyBytes + $publicKeyBytes
[IO.File]::WriteAllBytes($keyPath, $keypairBytes)
Write-Host "Identity keypair saved to: $keyPath" -ForegroundColor Green
Write-Host "Private key (hex): [BitConverter]::ToString($privateKeyBytes).Replace('-', '').ToLower()" -ForegroundColor DarkCyan
Write-Host "Public key (hex): [BitConverter]::ToString($publicKeyBytes).Replace('-', '').ToLower()" -ForegroundColor DarkCyan

# Step 3: Create configuration file
Write-Host "`nCreating configuration file..." -ForegroundColor Cyan
$configPath = Join-Path $tokenDir "config.toml"
$configContent = @"
# Solomon X Configuration
# Generated by bootstrap_token.ps1

[trust]
token_path = "$tokenPath"
identity_key_path = "$keyPath"

[memory]
hot_tier_path = "$tokenDir\\hot.db"
warm_tier_path = "$tokenDir\\warm.lancedb"
cold_tier_path = "$tokenDir\\cold"

[ui]
window_width = 1200
window_height = 800

[logging]
level = "info"
"@

[IO.File]::WriteAllText($configPath, $configContent)
Write-Host "Configuration saved to: $configPath" -ForegroundColor Green

Write-Host "`n=== Bootstrap Complete ===" -ForegroundColor Green
Write-Host "Next steps:" -ForegroundColor Yellow
Write-Host "1. Install dependencies: cargo install --path . (in solomon x directory)" -ForegroundColor Yellow
Write-Host "2. Start the daemon: .\target\release\solomon-daemon.exe" -ForegroundColor Yellow
Write-Host "3. Start the UI: cd ui && npm install && npm run dev" -ForegroundColor Yellow
Write-Host ""
Write-Host "NOTE: For actual TPM sealing, replace the token generation steps with:" -ForegroundColor Yellow
Write-Host "   tpm2_createprimary -C o -c primary.ctx" -ForegroundColor Yellow
Write-Host "   tpm2_create -C primary.ctx -u token.pub -r token.priv -i token_seed.bin" -ForegroundColor Yellow
Write-Host "   tpm2_load -C o -c token.ctx -u token.pub -r token.priv" -ForegroundColor Yellow
Write-Host "   tpm2_readpublic -c token.ctx" -ForegroundColor Yellow
Write-Host ""